### ISSUE TITLE
Handle error in Thymeleaf fragments

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/lib-thymeleaf#5]
The errors happening in thymeleaf fragments are not correctly handled. We get instead an "Invalid applicationKey file key uri specification" while handling the error. 

To reproduce:

Include a fragment
```
<div data-th-replace="../fragments/myfragment"></div> 
```

Loop over a missing array
```
<ul>
  <li data-th-each="myobject : ${data.missing}">
    Test
  </li>
</ul>
```

**Comment by aro** [comment]
See also this issue: https://github.com/enonic/xp/issues/4762
